#!/bin/bash

#
# Modified From: https://code.google.com/p/go-wiki/wiki/WindowsCrossCompiling
#

set -o errexit
set -o nounset

cd $GOROOT/src

for arch in 8 6; do
        for cmd in a c g l; do
                go tool dist install -v cmd/$arch$cmd
        done
done
exit 0
